### ISSUE TITLE
Can't change PDF page

### ISSUE THREAD

**Issue by xiaoxiao11200** [densen2014/BootstrapBlazor.PdfReader#1]
![X$LASXIJ}J~(80_ (46BO}1](https://user-images.githubusercontent.com/36879239/209517141-ffae8ea5-9f47-4e62-a778-a9c33ee4ea56.jpg)

can't change or setting initial page, it doesn't work.

**Comment by densen2014** [comment]
不好意思这么久才看到issue, 试试新版演示界面

Sorry so long to see your issue, try the new version of the demo 

https://blazor.app1.es/pdfReaders


![image](https://user-images.githubusercontent.com/8428709/216495519-ef6e6d7c-b223-48c9-9046-6fa1ecf0dc91.png)
