### ISSUE TITLE
Issue with ShowPdf. PdfReader is not showing new document. 

### ISSUE THREAD

**Issue by HarpunDK** [densen2014/BootstrapBlazor.PdfReader#12]
Hi, fist of all thank you for a great product.

I am experiencing a but that has been introduced in version 8.0.1. 
Version: 8.0.0 is working great. When calling ShowPdf with memorystream, the document show is updated.
When using version 8.0.1 or version 8.0.2, this seems not be the case. The origianl document is displayed, even after new memorystream is sent with ShowPdf. The PdfReader keep showing the original document and does not show the new document-content.

Let me know if you need more information.

**Comment by densen2014** [comment]
Can you provide the code you use? I will check it later.

**Comment by HarpunDK** [comment]
[BlazorApp2.zip](https://github.com/densen2014/BootstrapBlazor.PdfReader/files/14034781/BlazorApp2.zip)

Hi Alex, see the sample attached. This should be an isolated sample for you to see.
Please change from: <PackageReference Include="BootstrapBlazor.PdfReader" Version="8.0.2" /> and <PackageReference Include="BootstrapBlazor.PdfReader" Version="8.0.0" />

Clean the project between version switching. 
![image](https://github.com/densen2014/BootstrapBlazor.PdfReader/assets/8235893/c2d1b484-c974-4788-bd15-caea109abbdd)

Toggle between Sample 1 and Sample 2.
Let me know if you need further information and I will try and provide.

**Comment by densen2014** [comment]
Because the new version is cached stream, there may be problems. I will test it first.

**Comment by densen2014** [comment]
v8.0.3
- Fix ShowPdf cache issue
- ShowPdf add parameters, forceLoad, islocalFile
- Added ShowPdf(string localFileName) to render PDF from Local File

```
        <Button IsAsync="true" OnClick="@(() => ShowFile("fxf5kv2kjka8vfwgvim6.pdf"))">Sample 1</Button>
        <Button IsAsync="true" OnClick="@(() => ShowFile("mljq8tr2k29nbrbanmci.pdf"))">Sample 2</Button>

        <PdfReader @ref="PdfReader" StreamMode="true" Height="800px" ReadOnly="true" Debug="true" LocalFileName="@LocalFileName" AutoStreamMode="true" Toolbar="false" Statusbar="false"></PdfReader>

        <Badge>@ShowingSample</Badge>

        @code
        {
            private string? LocalFileName { get; set; } = null;
            private PdfReader? PdfReader { get; set; } = default!;

            private string? ShowingSample { get; set; }

            private async Task ShowFile(string fileName)
            {
                ShowingSample = fileName;
                //var fileContent = await File.ReadAllBytesAsync(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", fileName));
                //using var memStream = new MemoryStream(fileContent);
                //await PdfReader.ShowPdf(memStream);

                LocalFileName = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", fileName);
                if (PdfReader != null) await PdfReader.ShowPdf(LocalFileName);

            }
        }
```

**Comment by HarpunDK** [comment]
Hi @densen2014 , I've just had the pleasure of testing the new version. The issue/bug I've reported is no longer to be produced. Thank you for quick reaction and solving this issue.
