### ISSUE TITLE
Unhandled exception rendering component: Value cannot be null. (Parameter 'jsObjectReference')

### ISSUE THREAD

**Issue by jojinshallar** [densen2014/BootstrapBlazor.PdfReader#4]
我需要由外部传入pdf文档的路径，并在页面显示的时候加载并显示，代码如下所示：

@page "/fetchdata"
@using System.IO

<BootstrapBlazor.Components.PdfReader @ref="pdfreader" />

@code {
    BootstrapBlazor.Components.PdfReader pdfreader;
    [Inject]
    IWebHostEnvironment hostEnvironment { get; set; }

    [Parameter]
    public string PdfFile { get; set; }
    protected override Task OnInitializedAsync()
    {
        //测试直接初始化
        PdfFile= Path.Combine(hostEnvironment.WebRootPath, "file.pdf");
        return base.OnInitializedAsync();
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        if (firstRender)
        {
            System.Console.WriteLine("step1");
            byte[] datas = File.ReadAllBytes(PdfFile);
            System.Console.WriteLine("step2");
            //System.Console.WriteLine(Convert.ToBase64String(datas));

            /*
            //可以正常加载pdf文档
            await Task.Run(async () =>
            {
            await pdfreader.ShowPdf(new MemoryStream(datas));
            });
            */
            //加载pdf文档报错
            await pdfreader.ShowPdf(new MemoryStream(datas));
            System.Console.WriteLine("step3");
        }
    }
}

如果直接用await pdfreader.ShowPdf(new MemoryStream(datas));会报如下错误：
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Value cannot be null. (Parameter 'jsObjectReference')
      System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at BootstrapBlazor.Components.PdfReader.ShowPdf(Stream stream)
         at PdfReaderDemo.Pages.FetchData.OnAfterRenderAsync(Boolean firstRender) in C:\xxx\PdfReaderDemo\Pages\FetchData.razor:line 45
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'KnIGphxd8u3bi6Ef_a6CwkMoNdYxHkEqtH36GCYktro'.
      System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'jsObjectReference'))
       ---> System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at BootstrapBlazor.Components.PdfReader.ShowPdf(Stream stream)
         at PdfReaderDemo.Pages.FetchData.OnAfterRenderAsync(Boolean firstRender) in C:\xxx\PdfReaderDemo\Pages\FetchData.razor:line 45

或者

warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Value cannot be null. (Parameter 'jsObjectReference')
      System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at BootstrapBlazor.Components.PdfReader.ShowPdf(Stream stream)
         at PdfReaderDemo.Pages.FetchData.OnAfterRenderAsync(Boolean firstRender)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'hcY4dbQ_uqWUToQQjqAyRF1eoH5nAjOmqMIxE7Ebasc'.
      System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'jsObjectReference'))
       ---> System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at BootstrapBlazor.Components.PdfReader.ShowPdf(Stream stream)
         at PdfReaderDemo.Pages.FetchData.OnAfterRenderAsync(Boolean firstRender)
         --- End of inner exception stack trace ---

如果在新开的线程中调用await pdfreader.ShowPdf(new MemoryStream(datas));则可以正常显示。（但如果pdf文件比较大时【10几M】，则要在线程中先休眠几秒再调用showpdf才正常）

组件版本：BootstrapBlazor.PdfReader版本是7.1.8，.Net7。

请问这个问题有更好的解决方案吗？

**Comment by densen2014** [comment]
也许是blazor生命周期, 组件js还没就绪

直接使用看看会不会报错

```
<PdfReader @ref="pdfReader" FileName="Path.Combine(hostEnvironment.WebRootPath, "file.pdf")" StreamMode />
```

参考 https://github.com/densen2014/Densen.Extensions/blob/master/Demo/DemoShared/Pages/PdfReaders.razor.cs


组件逻辑你可以调试试试

https://github.com/densen2014/BootstrapBlazor.PdfReader/blob/master/src/BootstrapBlazor.PdfReader/PdfReader.razor.cs

**Comment by jojinshallar** [comment]
谢谢！调试可知是因为js还没有加载完成，组件的AfterRender事件还没有触发就调用了ShowPdf方法，此时Module对象为null。
解决方法：
在组件中添加Loaded事件，在Loaded事件触发后再调用ShowPdf方法，主要代码如下;
` /// <summary>
    /// 组件渲染加载完成后回调事件，ShowPdf方法需要在此后事件后调用才生效
    /// </summary>
    [Parameter]
    public EventCallback Loaded { get; set; }

    /// <summary>
    /// 组件是否已加载完成，包括JS脚本的加载
    /// </summary>
    public bool IsLoaded { get; private set; } = false;`

`  protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            Module = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./_content/BootstrapBlazor.PdfReader/app.js" + "?v=" + System.Reflection.Assembly.GetExecutingAssembly().GetName().Version);
            var userAgent = await Module!.InvokeAsync<string>("getUserAgent");
            var parser = Parser.GetDefault();
            ClientInfo = parser.Parse(userAgent);
            await Refresh();
            IsLoaded = true;
            await Loaded.InvokeAsync(this);
        }
    }`

` public virtual async Task ShowPdf(Stream stream)
    {
        if (Module is not null)
        {
            Url = null;
            var url = GenUrl(false);
            UrlDebug = url;
            using var streamRef = new DotNetStreamReference(stream);
            await Module!.InvokeVoidAsync("showPdf", url, Element, streamRef);
        }
    }`


https://github.com/densen2014/BootstrapBlazor.PdfReader/pull/5

**Comment by densen2014** [comment]
这样改就可以了

```
    /// <summary>
    /// 打开 stream
    /// </summary>
    public virtual async Task ShowPdf(Stream stream)
    {
        if (Module == null)
        {
            Stream=stream; 
        }
        else
        {
            Url = null;
            var url = GenUrl(false);
            UrlDebug = url;
            using var streamRef = new DotNetStreamReference(stream);
            await Module!.InvokeVoidAsync("showPdf", url, Element, streamRef);
        }
    }
```
demo

https://github.com/densen2014/Densen.Extensions/tree/%E4%BB%A3%E7%A0%81%E6%96%B9%E5%BC%8F%E5%8A%A0%E8%BD%BD%E6%96%87%E4%BB%B6%E6%B5%81
