### ISSUE TITLE
Data does not refresh when supplied Stream parameter is changed 

### ISSUE THREAD

**Issue by thabans** [densen2014/BootstrapBlazor.PdfReader#6]
Hi,

I updated the stream parameter to a new file and the pdf still displays old file. Only creating a new component would refresh it.

**Comment by densen2014** [comment]
ref=reader


reader. Refresh()

**Comment by densen2014** [comment]
are you still here?

**Comment by thabans** [comment]
Sorry for the late reply. It works.
