### ISSUE TITLE
搜索接口没有响应

### ISSUE THREAD

**Issue by HEYRIX** [densen2014/BootstrapBlazor.PdfReader#9]
目前在使用bootstrapblazor.PDFReader时，发现只有第一次进入pdf页面时可以做搜索且跳到对应页面。再次搜索就不再响应。https://www.blazor.zone/pdf-reader 使用这个页面的Demo也有同样问题，请问这是组件实现的bug么

外置搜索。
即调用 await pdfReader.Refresh(); 没有效果。

**Comment by densen2014** [comment]
https://blazor.app1.es/pdfReaders 你这里高级页面试试搜索
不确定是不是bb文档没更新

**Comment by densen2014** [comment]
v8.0.1
